name: SponsersCSV to JSON Conversion

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      csv_url:
        description: 'URL of the CSV file'
        required: true
        default: 'https://assets.publishing.service.gov.uk/media/67936e867b75412c254f4af1/2025-01-24_-_Worker_and_Temporary_Worker.csv'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run CSV to JSON conversion
      run: |
        python uk-sponsers/sponsers-json.py "${{ github.event.inputs.csv_url }}"